### ISSUE TITLE
Compile dssim for windows

### ISSUE THREAD

**Issue by lorents17** [pornel/dssim#15]
Hi!
Tell me, how to compile dssim for windows?

**Comment by pornel** [comment]
Use MinGW, make sure you have libpng available, and run `make`. 

Unfortunately I don't know Windows, so I can't give more precise instructions.

**Comment by lorents17** [comment]
All this I have done. It didn't help.

**Comment by lkwg82** [comment]
What about cross compile with a docker environment or sth similiar?

**Comment by lorents17** [comment]
Tell me how to do this? I'm not good at this

**Comment by cssignet** [comment]
most of pornel's projects are here : http://css-ig.net/tools/public/ including dssim 1.0 : http://css-ig.net/tools/public/dssim.zip

**Comment by lorents17** [comment]
Thank you very much!
