### ISSUE TITLE
question: dssim threshold

### ISSUE THREAD

**Issue by ebridges** [pornel/dssim#22]
We've been using your tool to aid in evaluating quality of JPEGs, and are really happy with how helpful its been.

The [only mention I could find](https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/) on what threshold to base our evaluations on indicates that a score of `0.015` reflects that the image pair is typically indistinguishable from each other.  However, their reference doesn't even mention anything about this (!).

Do you have any pointers to research done on this?  Do you have any opinions on a useful threshold, and/or do you agree with a value of `0.015`?

Thanks

**Comment by pornel** [comment]
That number is from a questionable marketing paper by RadWare. They haven't reported what version of DSSM they've used (and improvements to DSSIM accuracy have caused magnitude of these numbers to change), so it's basically meaningless.

However, it's easy to recreate it. Take an image that is representative for your use case, manually compress it to a quality you find good enough, and take DSSIM of that image a your threshold.

**Comment by ebridges** [comment]
I figured it was a dicey source based on them needing a registration to review it.  However, I went through the trouble to register and the actual link contains nothing about DSSIM, let alone any mention of measuring quality.  :shrug:

In any case, taking your suggestion, what would the DSSIM of the compressed image be done against -- the original?

Thanks

**Comment by pornel** [comment]
Yes, compare original source with the compressed.

**Comment by ebridges** [comment]
Terrific, thanks!
