### ISSUE TITLE
munmap_chunk error fixed in 1.3.1

### ISSUE THREAD

**Issue by nathanaeljones** [pornel/dssim#24]
Just logging that version 1.3.1 fixes the munmap_chunk error found in 1.1 (which is latest in ppa:lkwg82/dssim)

> n@nathanael-xeon:~/Documents/imazen/imageflow$ dssim /home/n/Documents/imazen/imageflow/tests/visuals/000000007E535E4D_000000000FA8D6DC.png /home/n/Documents/imazen/imageflow/tests/visuals/00000000AC6E6E56_000000000FA8D6DC.png
> *** Error in `dssim': munmap_chunk(): invalid pointer: 0x000000000201cc80 ***
> Aborted (core dumped)
> n@nathanael-xeon:~/Documents/imazen/imageflow$ pngcheck /home/n/Documents/imazen/imageflow/tests/visuals/000000007E535E4D_000000000FA8D6DC.png
> OK: /home/n/Documents/imazen/imageflow/tests/visuals/000000007E535E4D_000000000FA8D6DC.png (700x525, 32-bit RGB+alpha, non-interlaced, 52.7%).
> n@nathanael-xeon:~/Documents/imazen/imageflow$ pngcheck /home/n/Documents/imazen/imageflow/tests/visuals/00000000AC6E6E56_000000000FA8D6DC.png
> OK: /home/n/Documents/imazen/imageflow/tests/visuals/00000000AC6E6E56_000000000FA8D6DC.png (700x525, 32-bit RGB+alpha, non-interlaced, 51.0%).
> n@nathanael-xeon:~/Documents/imazen/imageflow$ dssim -v
> Usage: dssim original.png modified.png [modified.png...]
>    or: dssim -o difference.png original.png modified.png
> 
> Compares first image against subsequent images, and outputs
> 1/SSIM-1 difference for each of them in order (0 = identical).
> 
> Images must have identical size, but may have different gamma & depth.
> 
> Version 1.1 http://pornel.net/dssim

**Comment by pornel** [comment]
Thanks
