### ISSUE TITLE
Add .ppm support? 

### ISSUE THREAD

**Issue by nathanaeljones** [pornel/dssim#25]
png (de)compression is very slow for large images. Would it seem in scope to support .ppm or some other mem-dump format with no CPU overhead?

**Comment by pornel** [comment]
I suggest writing PNG without gzip instead, e.g.

```sh
convert blah.ppm -define png:compression-level=0 blah.png
```

**Comment by nathanaeljones** [comment]
When writing PNGs, I'm seeing 200ms for compression=Z_NO_COMPRESSIOn vs 372ms for Z_BEST_SPEED on a 24-bit 1600x1600 png.  Not insignificant, but still inexplicably slow.

**Comment by pornel** [comment]
If you need really fast writing, you could theoretically bypass zlib entirely and write IDAT. The only cost would be calculating CRCs.

If you need even faster, then use DSSIM in memory via C interface (see dssim.h). Then you won't need to touch the disk or any file format.

**Comment by pornel** [comment]
I think uncompressed PNG & C API are enough.
