### ISSUE TITLE
Create a new windows exe

### ISSUE THREAD

**Issue by JosePineiro** [pornel/dssim#26]
The compiled version for windows is very old.
Please, give a compile of the last verision or give a makefile.vc (makefile for microsoft visual C)

**Comment by pornel** [comment]
Sorry, I can't provide the binaries. I find Visual Studio impossible to use. There's nothing special about compiling dssim - just build all `.c` files and link with libpng.

**Comment by cssignet** [comment]
just in case, this 1.3.2 should work : http://css-ig.net/tools/public/dssim.zip

**Comment by pornel** [comment]
Thanks @cssignet! Can you share your project files, so that I can build these tools myself?

**Comment by cssignet** [comment]
i do not use those tools, i did this from mingw.

**Comment by cssignet** [comment]
1.3.2 with jpg support : http://css-ig.net/tools/public/dssim.zip

**Comment by shtse8** [comment]
Hi everyone, I need windows version too. Any updates?
The download link above isn't work.

**Comment by shtse8** [comment]
How to build it for windows using Visual Studio?

**Comment by pornel** [comment]
Done. The new 2.8.0 works on Windows out of the box thanks to Rust being portable.
