### ISSUE TITLE
Add GitHub releases for new tags

### ISSUE THREAD

**Issue by swernerx** [pornel/dssim#27]
The last official release on Github is 1.1 while there are newer tags. Would you please offer releases with source archives for integration with homebrew?Thga

https://github.com/Homebrew/homebrew-core/pull/1004

**Comment by swernerx** [comment]
Okay, that does not seem to be relevant for the archives. Archives are available for tags, too. Would just be nice to have some changelog though.

**Comment by pornel** [comment]
I've updated tag descriptions and added bin https://github.com/pornel/dssim/releases/tag/1.3.2
