### ISSUE TITLE
dssim != 0 when comparing 2 all black images

### ISSUE THREAD

**Issue by rcanavan** [pornel/dssim#30]
dssim finds differences in the two all black (as far as I can tell) PNGs below, i.e. instead of 0.000000 it prints 0.03023894. One of the images is truecolor, the other is grayscale. Both were generated with ImageMagick 7.0.2-1 using libpng 1.2.54-1ubuntu1, cropped from the same source image, but one was converted to a jpeg with quality 70 before cropping.

![a](https://cloud.githubusercontent.com/assets/4719149/17940377/13226d68-6a2f-11e6-9302-207d78abe2dd.png)
![b](https://cloud.githubusercontent.com/assets/4719149/17940383/191910d2-6a2f-11e6-9cdc-03837bd7ed07.png)

**Comment by pornel** [comment]
Yup, there's some off-by-one or memory error in there. Might be same as #29

**Comment by pornel** [comment]
Please try v2.8.0 1e4760418c1b8a47a26b325d1e28761e46cd9522
