### ISSUE TITLE
Can't read input file

### ISSUE THREAD

**Issue by pixelastic** [pornel/dssim#32]
Hello,

This might be related to my currently installed version of libpng (cf #31), but I can't seem to be able to compare any two png files.

No matter what files I pass as parameters, `dssim` fails with the following message:

```
Can't read ./input.png
```

FWIW, here are the two files I used in my tests (hoping that uploading them to GitHub won't modify them too much):
![image](https://cloud.githubusercontent.com/assets/283419/18619918/30687cea-7e08-11e6-889a-306eef4b8b54.png)![image](https://cloud.githubusercontent.com/assets/283419/18619919/356d3b7c-7e08-11e6-8dda-33ec838e4761.png) 
(md5sum: e26f1b5fb954a82ce9e514026330a415 and ec0d02893bd1c92978527071f5505263)

**Comment by pornel** [comment]
I've updated master to show the error number. If you have two libpng versions on the system it could happen that the program was compiled with headers from the new libpng, but linked with libs from the old one, which makes it fail at run time.

**Comment by pixelastic** [comment]
I cleaned up my dependencies, removed the `bin` dir and ran `make` again and `dssim` is working as expected now.

Thanks for the help :)
