### ISSUE TITLE
to_dssim: Assertion `ssim > 0' failed.

### ISSUE THREAD

**Issue by rcanavan** [pornel/dssim#40]
I get `dssim: src/dssim.c:663: to_dssim: Assertion `ssim > 0' failed.` for a pair of handmade 320x320 test images, and apparently the choice of colors matters. I haven't tested any less garish colors, nor if the red border is in any way relevant. 

```
$ ./bin/dssim  yellow_darkblue.png  green_blue.png 
dssim: src/dssim.c:663: to_dssim: Assertion `ssim > 0' failed.
Aborted (core dumped)
$ ./bin/dssim  blue_darkblue.png green_blue.png 
0.42122125      green_blue.png
$ ./bin/dssim  blue_darkblue.png yellow_darkblue.png 
0.49453378      yellow_darkblue.png
```

![blue_darkblue](https://cloud.githubusercontent.com/assets/4719149/25238551/0db0e622-25ee-11e7-9932-425924fc46b1.png)
![green_blue](https://cloud.githubusercontent.com/assets/4719149/25238550/0daf8f0c-25ee-11e7-9146-25304f9d99cd.png)
![yellow_darkblue](https://cloud.githubusercontent.com/assets/4719149/25238552/0db6871c-25ee-11e7-8496-c6459cd66dc3.png)

**Comment by rcanavan** [comment]
Since the individual ssim values for each pixel calculated in the loop in `dssim_compare_channel` can be both > 1 ((more equal than equal!), see the color picker image below) or < 0 (images above), we are currently  using the following workaround:
```
@@ -748,9 +750,11 @@ static double dssim_compare_channel(const dssim_chan *restrict original, dssim_c
         const double sigma2_sq = img2_sq_blur[offset] - mu2_sq;
         const double sigma12 = img1_img2_blur[offset] - mu1_mu2;
 
-        const double ssim = (2.0 * mu1_mu2 + c1) * (2.0 * sigma12 + c2)
+
+
+        const double ssim = MIN(MAX((2.0 * mu1_mu2 + c1) * (2.0 * sigma12 + c2)
                       /
-                      ((mu1_sq + mu2_sq + c1) * (sigma1_sq + sigma2_sq + c2));
+                      ((mu1_sq + mu2_sq + c1) * (sigma1_sq + sigma2_sq + c2)), 0), 1.0);
 
         ssim_sum += ssim;
```
![color-picker-black](https://cloud.githubusercontent.com/assets/4719149/25284638/edb4d0ac-26b7-11e7-896a-faeae1947ac4.png)

**Comment by asarubbo** [comment]
I get also an undefined behavior:
src/dssim.c:715:30: runtime error: division by zero

**Comment by pornel** [comment]
Please try 2.8.0

1e4760418c1b8a47a26b325d1e28761e46cd9522
