### ISSUE TITLE
Possibility to fine tune parameters? / dssim ignores obvious distortion (probably because of chroma subsampling)

### ISSUE THREAD

**Issue by magicgoose** [pornel/dssim#42]
For example:
• compare chroma in full resolution (without subsampling) — useful for images where subsampling of chroma is actually visible
• making the comparison single-scale — useful for use cases where it is definitely known that only small details might change

**Comment by pornel** [comment]
Full-res chroma mixed with values for other channels gives too much weight on color noise. It would need adjustment how the score is mixed with other channels/scales.

I also wonder whether there should be something more intelligent to detect color fringing, since that's seems like a case of a special correlation between channels.

If only small details change, then difference in other scales will be 0, so they won't affect relative score.

**Comment by magicgoose** [comment]
> It would need adjustment how the score is mixed with other channels/scales.

Yes, this will be needed then too, of course. Maybe a simple multiplier for the top chroma scale could be adequate.

> I also wonder whether there should be something more intelligent to detect color fringing, since that's seems like a case of a special correlation between channels.

I am not sure a special logic is needed for this, color fringing is just another visual feature which is as visible as others…

> If only small details change, then difference in other scales will be 0, so they won't affect relative score.

👍

**Comment by magicgoose** [comment]
@pornel 
I have found real world image(s) where dssim gives obviously inadequate results.  
https://drive.google.com/drive/folders/1qKl1rKDFxAnFUHyVOvjMqEmPvd5J3TIw — link to g.drive with all 3 files, the original uncompressed photo (made from raw) and 2 differently made jpegs from it.

dssim(source, jpg_1x1_q95) = 0.00054388  
dssim(source, jpg_2x2_q100) = 0.00028169

it implies that the second image (jpg_2x2_q100) is visually closer to the source (about 2 times), but in reality it has a lot more obvious distortion (blur and "blocking" artifacts) while the first (jpg_1x1_q95) is just fine and hard to distinguish from source visually.

The difference between these jpeg files is that second one uses 2x2 chroma subsampling and the first one doesn't.  
Details in red-colored areas are seriously butchered by chroma subsampling in jpeg (I don't know exactly why but it's clearly visible in this case), and looks like dssim does the subsampling in the similar way so it doesn't see what is lost in these cases.

**Comment by pornel** [comment]
OK, it's fixed in 2.8.0. It now uses full-res chroma:

0.001925	dssim_test/jpg_2x2_q100.jpg
0.001050	dssim_test/jpg_1x1_q95.jpg
