### ISSUE TITLE
error: Could not compile `rayon-core`.

### ISSUE THREAD

**Issue by sarya-alsayed** [pornel/dssim#44]
when i try to build dssim and type this command on Ubuntu bash : 
`cargo build --release --verbose
`
i get this error 
`error: Could not compile rayon-core`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.3.0/build.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=29a42b65b777dc05 -C extra-filename=-29a42b65b777dc05 --out-dir /mnt/d/sarya2017/dssim/target/release/build/rayon-core-29a42b65b777dc05 -L dependency=/mnt/d/sarya2017/dssim/target/release/deps --cap-lints allow` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed`

i dont know what the problem , Any help i appreciate it

**Comment by pornel** [comment]
This error is very unspecific. Perhaps you're compiling it in a VM that doesn't have enough memory?

**Comment by sarya-alsayed** [comment]
my operating system is windows 10 and i compiling it on Ubuntu bash on windows , not on VM  ,

**Comment by sarya-alsayed** [comment]
thanks , i installed gcc for compiling , this solved the issue .
